_BASE_: "Base-BlendMask.yaml"
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  # MIN_SIZE_TRAIN: (512, 512)
  MAX_SIZE_TRAIN: 900 #900
  MAX_SIZE_TEST: 736  #736
  MIN_SIZE_TEST: 512  #512
MODEL:
  FCOS:
    TOP_LEVELS: 0
    SIZES_OF_INTEREST: [64, 128]
    FPN_STRIDES: [8, 16, 32]
    IN_FEATURES: ['p3', 'p4', 'p5']
SOLVER:
  STEPS: (300000, 340000)
  MAX_ITER: 360000